export default function AboutPage() {
  return (
    <div className="page-enter">
      <section style={{ padding: "72px 0 56px", borderBottom: "1px solid var(--border)" }}><div className="container" style={{ maxWidth: 920 }}><div className="eyebrow" style={{ color: "var(--accent)", marginBottom: 15 }}>О редакции</div><h1 style={{ fontSize: "clamp(36px,6vw,60px)", lineHeight: 1.1, letterSpacing: "-.03em", maxWidth: 820, color: "var(--text)" }}>Новости<br /><span style={{ color: "var(--accent)" }}>технологий.</span></h1><p style={{ color: "var(--text-muted)", fontSize: 19, lineHeight: 1.6, maxWidth: 680, marginTop: 22 }}>TechStream.kz — сайт о технологиях, искусственном интеллекте, цифровой экономике и инновациях Казахстана и мира.</p></div></section>
      <section style={{ padding: "56px 0 80px" }}><div className="container"><div className="about-grid" style={{ display: "grid", gridTemplateColumns: "1.2fr .8fr", gap: 48, alignItems: "start" }}><div><div className="eyebrow" style={{ color: "var(--accent)", marginBottom: 10 }}>Наша миссия</div><h2 style={{ fontSize: 30, marginBottom: 18, color: "var(--text)" }}>Помогать понимать сложное</h2><div className="about-copy"><p>Мы собираем важные технологические новости, проверяем факты и объясняем контекст простым языком. В фокусе редакции — то, как технологии меняют бизнес, государство и повседневную жизнь.</p><p>Мы внимательно следим за развитием цифровой экосистемы Казахстана и одновременно смотрим на глобальные тренды — от искусственного интеллекта и кибербезопасности до космических технологий и новых устройств.</p></div></div><div style={{ padding: 28, borderRadius: "var(--radius-lg)", border: "1px solid var(--border)", background: "var(--bg-soft)" }}><div className="eyebrow" style={{ color: "var(--accent)", marginBottom: 18 }}>Связаться с редакцией</div><div style={{ display: "flex", flexDirection: "column", gap: 17 }}><div><div style={{ color: "var(--text-muted)", fontSize: 12, marginBottom: 4 }}>Email</div><a href="mailto:techstreamkz@gmail.com" style={{ color: "var(--accent)", fontSize: 16, fontWeight: 600 }}>techstreamkz@gmail.com</a></div><div><div style={{ color: "var(--text-muted)", fontSize: 12, marginBottom: 4 }}>Телефон</div><a href="tel:+77476983191" style={{ color: "var(--text)", fontSize: 16, fontWeight: 600 }}>+7 747 698 3191</a></div><div><div style={{ color: "var(--text-muted)", fontSize: 12, marginBottom: 4 }}>Город</div><span style={{ color: "var(--text-soft)", fontSize: 15 }}>Алматы, Казахстан</span></div></div></div></div></div></section>
      <style>{`.about-copy p{color:var(--text-muted);font-size:18px;line-height:1.75;margin-bottom:20px}@media(max-width:750px){.about-grid{grid-template-columns:1fr!important;gap:30px!important}}`}</style>
    </div>
  );
}
